version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - apt-get update
      - apt-get install nginx -y
  build:
    commands:
      - echo "Build started on $(date)"
      - mkdir -p /tmp/nginx/
      - cp index.html /tmp/nginx/
  post_build:
    commands:
      - echo "Configuring NGINX"
artifacts:
  files:
    - "**/*"
